spring:
  application:
     name: ${vcap.application.application_name:cities}
  jpa:
     hibernate:
        show-sql: false
        ddl-auto: none
security:
  basic:
    enabled: false
---
spring:
  profiles: default
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
